{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "55dbbcdd-fce7-4614-838c-354adddfb23a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Simple Command-Line Calculator in Python\n",
    "\n",
    "def add(a, b):\n",
    "    return a + b  # Returns the sum of two numbers\n",
    "\n",
    "def subtract(a, b):\n",
    "    return a - b  # Returns the difference between two numbers\n",
    "\n",
    "def multiply(a, b):\n",
    "    return a * b  # Returns the product of two numbers\n",
    "\n",
    "def divide(a, b):\n",
    "    if b == 0:\n",
    "        return \"Error: Cannot divide by zero.\"  # Handles division by zero\n",
    "    return a / b  # Returns the quotient\n",
    "\n",
    "def modulo(a, b):\n",
    "    if b == 0:\n",
    "        return \"Error: Cannot perform modulo with zero.\"  # Handles modulo by zero\n",
    "    return a % b  # Returns the remainder\n",
    "\n",
    "def get_number(prompt):\n",
    "    # Keeps asking for input until a valid number is entered\n",
    "    while True:\n",
    "        try:\n",
    "            return float(input(prompt))  # Accepts both integers and decimals\n",
    "        except ValueError:\n",
    "            print(\"Invalid input. Please enter a number.\")\n",
    "\n",
    "def display_menu():\n",
    "    # Displays the calculator menu\n",
    "    print(\"\\nSelect an operation:\")\n",
    "    print(\"1. Addition\")\n",
    "    print(\"2. Subtraction\")\n",
    "    print(\"3. Multiplication\")\n",
    "    print(\"4. Division\")\n",
    "    print(\"5. Modulo\")\n",
    "    print(\"6. Exit\")\n",
    "\n",
    "def main():\n",
    "    while True:\n",
    "        display_menu()\n",
    "        choice = input(\"Enter your choice (1-6): \")\n",
    "\n",
    "        if choice == '6':\n",
    "            print(\"Exiting the calculator. Goodbye!\")\n",
    "            break  # Exit the loop and program\n",
    "\n",
    "        if choice not in ['1', '2', '3', '4', '5']:\n",
    "            print(\"Invalid choice. Please select a valid option (1-6).\")\n",
    "            continue  # Ask again if input is invalid\n",
    "\n",
    "        # Get two numbers from the user\n",
    "        num1 = get_number(\"Enter the first number: \")\n",
    "        num2 = get_number(\"Enter the second number: \")\n",
    "\n",
    "        # Perform the selected operation\n",
    "        if choice == '1':\n",
    "            result = add(num1, num2)\n",
    "        elif choice == '2':\n",
    "            result = subtract(num1, num2)\n",
    "        elif choice == '3':\n",
    "            result = multiply(num1, num2)\n",
    "        elif choice == '4':\n",
    "            result = divide(num1, num2)\n",
    "        elif choice == '5':\n",
    "            result = modulo(num1, num2)\n",
    "\n",
    "        print(f\"Result: {result}\")  # Display the result\n",
    "\n",
    "# Run the main function when the script is executed\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
